imports:
    - { resource: '@ModeraSecurityBundle/Resources/config/config.yaml' }
    - { resource: '@ModeraSecurityBundle/Resources/config/firewalls.yaml' }

security:
    firewalls: '%modera_security.config.firewalls%'
    access_control: '%modera_security.config.access_control%'
